### ISSUE TITLE
test

### ISSUE THREAD

**Issue by TammyLewis** [AaronLayton/ViewEnginePlus#11]
http://www.bugherd.com/projects/67694/tasks/1

**Comment by TammyLewis** [comment]
test

**Comment by TammyLewis** [comment]
test

**Comment by TammyLewis** [comment]
Test from GitHub

**Comment by TammyLewis** [comment]
Test from BH

**Comment by TammyLewis** [comment]
Closes BH-1

**Comment by AaronLayton** [comment]
Not sure it will close like that ? Should work from a Commit message though

**Comment by TammyLewis** [comment]
Dome some stuff - fixes #11 closes BH-1
